{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xapi-lrs.fullname" . }}
  labels:
    {{- include "xapi-lrs.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  admin-password: {{ .Values.auth.adminPassword | b64enc | quote }}
  session-secret: {{ include "xapi-lrs.sessionSecret" . | b64enc | quote }}
  postgresql-password: {{ .Values.database.postgresql.password | b64enc | quote }}
  migration-postgresql-password: {{ .Values.migration.postgresql.password | default .Values.database.postgresql.password | b64enc | quote }}
  {{- if .Values.auth.apiSecret }}
  api-secret: {{ .Values.auth.apiSecret | b64enc | quote }}
  {{- end }}
{{- end }}
