provider:
  name: od360-sandbox--keycloak-provider
  secretName: od360-sandbox--keycloak-provider-creds

realm:
  name: od360-sandbox
  forProvider:
    enabled: true
    defaultSignatureAlgorithm: "RS256"
    loginWithEmailAllowed: true
    resetPasswordAllowed: true
    registrationAllowed: false
    verifyEmail: false
    accessCodeLifespanUserAction: "15m0s"
    smtpServer:
      - auth:
          - passwordSecretRef:
              key: KEYCLOAK_OD360_SMTP_PASSWORD
              name: keycloak-smtp-config
              namespace: "{{ tpl .Values.realm.name $ }}"
            username: "AKIAQB4RZGLOWCFLPQ5K"
        envelopeFrom: ""
        from: "no-reply@opendash360.us"
        fromDisplayName: ""
        port: "465"
        host: "email-smtp.us-gov-west-1.amazonaws.com"
        replyTo: ""
        replyToDisplayName: ""
        ssl: true
        starttls: true

builtinObjects:
  spec:
    builtinClients:
      - realm-management
      - account
    builtinRealmRoles: []
    builtinAuthenticationFlows: []

clients:
  oidc:
    - name: "opendash360-public"
      forProvider:
        accessType: "PUBLIC"
        clientId: opendash360-public
        description: "OpenDash360 client opendash360-public"
        directAccessGrantsEnabled: true
        enabled: true
        validRedirectUris: ["*"]
        standardFlowEnabled: true
        webOrigins: ["*"]
      scope:
        name: "od360"
        forProvider:
          name: od360
          includeInTokenScope: true
        mappers:
          - name: "orgpath"
            forProvider:
              name: orgpath
              config:
                access.token.claim: "true"
                aggregate.attrs: "false"
                claim.name: "od360.orgpath"
                id.token.claim: "true"
                jsonType.label: "String"
                multivalued: "false"
                user.attribute: "orgPath"
                userinfo.token.claim: "true"
          - name: "ltabyuser"
            forProvider:
              name: ltabyuser
              config:
                access.token.claim: "true"
                aggregate.attrs: "false"
                claim.name: "od360.ltaByUser"
                id.token.claim: "true"
                jsonType.label: "String"
                multivalued: "false"
                user.attribute: "ltaByUser"
                userinfo.token.claim: "true"
          - name: "ltabyuser"
            forProvider:
              name: ltabyuser
              config:
                access.token.claim: "true"
                aggregate.attrs: "false"
                claim.name: "od360.ltaByUser"
                id.token.claim: "true"
                jsonType.label: "String"
                multivalued: "false"
                user.attribute: "ltaByUser"
                userinfo.token.claim: "true"

      defaultScope:
        name: "opendash360-public"
        forProvider:
          defaultScopes:
            - od360
            - roles
            - web-origins
            - profile
            - acr
            - email
            - basic

roles:
  - name: "administrator"
    forProvider:
      name: Administrator
      description: "Administrator role"
      compositeRolesRefs:
        - name: "builtin-{{ tpl .Values.realm.name $ }}-create-client"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-impersonation"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-authorization"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-clients"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-events"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-identity-providers"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-users"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-query-clients"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-query-groups"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-query-realms"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-query-users"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-realm-admin"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-authorization"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-clients"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-events"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-identity-providers"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-realm"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-users"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-delete-account"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-account"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-account-links"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-consent"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-applications"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-consent"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-groups"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-profile"
  - name: "approved"
    forProvider:
      name: Approved
      description: "Identifies approved users"
  - name: "opendash-admins"
    forProvider:
      name: opendash_admins
      description: "newer Administrator role"
      compositeRolesRefs:
        - name: "builtin-{{ tpl .Values.realm.name $ }}-create-client"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-impersonation"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-authorization"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-clients"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-events"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-identity-providers"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-users"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-query-clients"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-query-groups"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-query-realms"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-query-users"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-realm-admin"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-authorization"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-clients"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-events"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-identity-providers"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-realm"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-users"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-delete-account"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-account"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-account-links"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-manage-consent"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-applications"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-consent"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-groups"
        - name: "builtin-{{ tpl .Values.realm.name $ }}-view-profile"
  - name: "opendash-assessor"
    forProvider:
      name: opendash_assessor
      description: "Assessor Role"
  - name: "opendash-lms-admins"
    forProvider:
      name: opendash_lms_admins
      description: "LMS Role"
  - name: "opendash-quiz-author"
    forProvider:
      name: opendash_quiz_author
      description: "Quiz Author Role"
  - name: "opendash-resource-manager"
    forProvider:
      name: opendash_resource_manager
      description: "Opendash Resource Manager"
  - name: "opendash-training-certifier"
    forProvider:
      name: opendash_training_certifier
      description: "Training Certifier role"
  - name: "opendash-workforce-manager"
    forProvider:
      name: opendash_workforce_manager
      description: "Workforce manager role"
  - name: "opendash-integration"
    forProvider:
      name: opendash_integration
      description: "Role for use by external partners"

userFederation:
  ldap:
    enabled: true
    name: "freeipa"
    suffix: "$$ldap.suffix"
    bind:
      user: sso.svc
      dn: "uid={{ .Values.userFederation.ldap.bind.user }},cn=users,cn=accounts,{{ tpl .Values.userFederation.ldap.suffix $ }}"
    forProvider:
      connectionUrl: "ldap://{{ tpl .Values.realm.name $ }}-freeipa"
      bindCredentialSecretRef:
        namespace: "{{ tpl .Values.realm.name $ }}"
        name: keycloak-ldap-bind-creds
        key: KEYCLOAK_LDAP_BIND_PASSWORD
      rdnLdapAttribute: "uid"
      userObjectClasses:
        - top
        - person
        - organizationalperson
        - inetorgperson
        - posixaccount
        - inetuser
        - krbprincipalaux
        - krbticketpolicyaux
        - ipaobject
        - ipasshuser
        - mtouser
        - ipauser
        - ipaSshGroupOfPubKeys
        - mepOriginEntry
        - ipantuserattrs
      usernameLdapAttribute: "uid"
      usersDn: "cn=users,cn=accounts,{{ tpl .Values.userFederation.ldap.suffix $ }}"
      uuidLdapAttribute: "uid"
      vendor: "RHDS"

    mappers:
      userAttributeMappers:
        - name: givenname
          forProvider:
            name: "firstName <-> givenName"
            ldapAttribute: "givenName"
            userModelAttribute: "firstName"
            isBinaryAttribute: false
            isMandatoryInLdap: true
        - name: orgpath
          forProvider:
            name: "orgpath"
            ldapAttribute: "orgpath"
            userModelAttribute: "orgPath"
            isBinaryAttribute: false
        - name: krbprincipal
          forProvider:
            name: "krbPrincipalName"
            ldapAttribute: "krbPrincipalName"
            userModelAttribute: "email"
            isBinaryAttribute: false
            isMandatoryInLdap: true
        - name: creationdate
          forProvider:
            name: "create timestamp"
            ldapAttribute: "createTimestamp"
            userModelAttribute: "createTimestamp"
            isBinaryAttribute: false
            isMandatoryInLdap: false
        - name: email
          forProvider:
            name: "email"
            ldapAttribute: "mail"
            userModelAttribute: "email"
            alwaysReadValueFromLdap: true
            isBinaryAttribute: false
            isMandatoryInLdap: true
        - name: firstname
          forProvider:
            name: "first name"
            ldapAttribute: "cn"
            userModelAttribute: "firstName"
            isBinaryAttribute: false
            isMandatoryInLdap: true
        - name: lastname
          forProvider:
            name: "last name"
            ldapAttribute: "sn"
            userModelAttribute: "lastName"
            isBinaryAttribute: false
            isMandatoryInLdap: true
        - name: modifydate
          forProvider:
            name: "modify date"
            ldapAttribute: "modifyTimestamp"
            userModelAttribute: "modifyTimestamp"
            isBinaryAttribute: false
            isMandatoryInLdap: false
        - name: username
          forProvider:
            name: "username"
            ldapAttribute: "uid"
            userModelAttribute: "username"
            isBinaryAttribute: false
            isMandatoryInLdap: true
        - name: ltabyuser
          forProvider:
            name: "ltabyuser"
            ldapAttribute: "ltabyuser"
            userModelAttribute: "ltaByUser"
            alwaysReadValueFromLdap: true
            isBinaryAttribute: false
            isMandatoryInLdap: false
        - name: sponsoredbyuser
          forProvider:
            name: "sponsoredbyuser"
            ldapAttribute: "sponsoredbyuser"
            userModelAttribute: "sponsoredByUser"
            alwaysReadValueFromLdap: true
            isBinaryAttribute: false
            isMandatoryInLdap: false

      hardcodedAttributeMappers:
        - name: gidnumber
          forProvider:
            name: "hardcode-gidNumber"
            attributeName: "gidNumber"
            attributeValue: "99999999"
        - name: ipantsecurity
          forProvider:
            name: "hardcode-ipantsecurityidentifier"
            attributeName: "ipantsecurityidentifier"
            attributeValue: "JUNK_VALUE"
        - name: homedirectory
          forProvider:
            name: "hardcode-homeDirectory"
            attributeName: "homeDirectory"
            attributeValue: "/home/temp"
        - name: uidnumber
          forProvider:
            name: "hardcode-uidNumber"
            attributeName: "uidNumber"
            attributeValue: "99999999"

users:
  - forProvider:
      username: emmanuel.gomez
      email: emmanuel@pelo.tech
    roles:
      names:
        - opendash-admins
