apiVersion: v2
name: calendso
description: A Helm chart for Calendso
type: application

version: 0.1.0
appVersion: "latest"

dependencies:
  # https://github.com/bitnami/charts/tree/master/bitnami/postgresql
  - name: postgresql
    version: 10.9.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled