{{- if eq .Values.externalConfigSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calendso.fullname" . }}-base-env
  labels:
    {{- include "calendso.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ include "calendso.databaseURL" . | b64enc | quote }}
  BASE_URL: {{ .Values.config.baseURL | b64enc | quote }}
  NEXTAUTH_URL: {{ .Values.config.nextAuthURL | b64enc | quote }}
  NEXT_PUBLIC_TELEMETRY_KEY: {{ include "calendso.telemetryKey" . | b64enc | quote }}
  EMAIL_FROM: {{ .Values.config.email.from | b64enc | quote }}
  EMAIL_SERVER_HOST: {{ .Values.config.email.smtpHost | b64enc | quote }}
  EMAIL_SERVER_PORT: {{ .Values.config.email.smtpPort | b64enc | quote }}
{{- end }}