apiVersion: v2
name: postgrest
icon: https://docs.postgrest.org/en/v14/_images/postgrest.png
version: 0.7.0
maintainers:
  - name: jared-prime
    email: jared.davis@pelo.tech
  - name: apkatsikas
    email: andrew.katsikas@pelo.tech
description: Helm chart for a PostgREST data api.
appVersion: "v14.16"
