{{- $providerConfigName := tpl .Values.providerConfig.name $ | required ".Values.providerConfig.name is required" }}
{{- $realmName := tpl .Values.realm.name $ | printf "%s--realm" }}
---
apiVersion: keycloak.crossplane.io/v1alpha1
kind: XBuiltinObjects
metadata:
  name: "{{ $realmName }}-keycloak-builtin-objects"
spec:
  providerConfigName: "{{ $providerConfigName }}"
  providerSecretName: "{{ $realmName }}--keycloak-provider-credentials"
  realm: "{{ $realmName }}"
  {{- tpl (.Values.builtinObjects.spec | toYaml) $ | nindent 2 }}
