# Default values for backstage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

envSecret: ""

global:
  nodeSelector: {}

frontend:
  enabled: true
  appDirectory: /usr/share/nginx/html/static
  replicaCount: 1
  image:
    repository: martinaif/backstage-k8s-demo-frontend
    tag: test1
    pullPolicy: IfNotPresent
  containerPort: 80
  resources:
    requests:
      memory: 128Mi
    limits:
      memory: 256Mi

backend:
  enabled: true
  appDirectory: /usr/src/app
  nodeEnv: development
  demoData: true
  replicaCount: 1
  image:
    repository: martinaif/backstage-k8s-demo-backend
    tag: test1
    pullPolicy: IfNotPresent
  containerPort: 7000
  secretMounts: []
  resources:
    requests:
      memory: 512Mi
    limits:
      memory: 1024Mi

nameOverride: ''
fullnameOverride: ''

ingress:
  host: example.com
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($scheme = https) {
      add_header  Strict-Transport-Security "max-age=0;";
      }

appConfig: {}