apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.serviceName" . }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.backend.containerPort }}
  selector:
    app: backstage
    component: backend
  type: ClusterIP