{{- $newAPI := .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
{{- if $newAPI -}}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "backstage.fullname" . }}-ingress
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
    - secretName: {{ include "backstage.fullname" . }}-tls
      hosts:
        - {{ .Values.ingress.host }}

  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            {{- if $newAPI }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if $newAPI }}
              service:
                name: {{ include "frontend.serviceName" . }}
                port:
                  number: 80
              {{- else }}
              serviceName: {{ include "frontend.serviceName" . }}
              servicePort: 80
              {{- end }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            {{- if $newAPI }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if $newAPI }}
              service:
                name: {{ include "backend.serviceName" . }}
                port:
                  number: 80
              {{- else }}
              serviceName: {{ include "backend.serviceName" . }}
              servicePort: 80
              {{- end }}
 