apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrest
  namespace: {{ .Release.Namespace }}
data:
  PGRST_DB_ANON_ROLE: {{ .Values.application.anon | quote }}
  PGRST_DB_SCHEMAS: {{ .Values.application.schemas | quote }}
  {{- if .Values.application.preRequest }}
  PGRST_DB_PRE_REQUEST: {{ .Values.application.preRequest | quote }}
  {{- end }}
  PGRST_JWT_ROLE_CLAIM_KEY: {{ .Values.application.jwt.claim.selector | quote }}
  {{- if or .Values.probes.startup.enabled .Values.probes.liveness.enabled }}
  PGRST_ADMIN_SERVER_PORT: {{ .Values.containerPorts.admin | quote }}
  {{- end }}
  {{- if .Values.jwks.enabled }}
  PGRST_JWT_SECRET: {{ printf "@%s" (include "postgrest.jwks.path" .) | quote }}
  {{- end }}

{{- if .Values.jwks.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgrest-jwks
  namespace: {{ .Release.Namespace }}
data:
  fetch-jwks.sh: |
{{ .Files.Get "files/fetch-jwks.sh" | indent 4 }}
{{- end }}
