name: pre-commit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: install pre-commit
        run: pip install pre-commit

      - name: Build dependencies Helm - lrsql
        uses: WyriHaximus/github-action-helm3@e3894d973c282349e3d41d3347767f2b2545b583 # v4
        with:
          exec: helm dependency build charts/lrsql

      - name: pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
