apiVersion: v1
kind: Service
metadata:
  name: {{ include "umami.fullname" . }}
  labels:
    {{- include "umami.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.targetPort.http }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.http)) }}
      nodePort: {{ .Values.service.nodePorts.http }}
      {{- end }}
    {{- if .Values.sso.enabled }}
    - name: sso-http
      port: {{ .Values.service.ports.sso }}
      targetPort: {{ .Values.service.targetPort.sso }}
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.sso)) }}
      nodePort: {{ .Values.service.nodePorts.sso }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "umami.selectorLabels" . | nindent 4 }}
